### PR TITLE
Levenshtein search

### PR DESCRIPTION
**Pull request by mDantas**
## Summary
Be able to do approximate string searching in`O(n*m + n +m)`*:
```javascript
var s = 'The RainCoat BookStore';
var t = 'All the best books are here at the Rain Coats Book Store';
n.LevenshteinDistance(s, t)
 => { substring: 'the Rain Coats Book Store', distance: 4 }
```

## Details
This PR expands the existing Levenshtein Distance function to do approximate string searching as described in [this Wikipedia article](https://en.wikipedia.org/wiki/Approximate_string_matching#Problem_formulation_and_algorithms).

The main difference between using Levenshtein for distance calculation vs searching is (1) initializing the first row of the distance matrix with `0`s and (2) keeping track of the parent of each distance cell (i.e. is the current cell's cost a result of insertion/deletion/substitution). Then, do Levenshtein as usual.

With the distance matrix filled out, find the minimum value in the last row of the matrix. This will be the end of the closest substring match. Then walk back from this cell to the first row. The column position of the cell to which you've arrived in the first row is the start of the closest substring match.

## Why
This felt like an easy way to augment `natural`'s existing functionality to provide for pretty fast* approximate string searching.

 *`O(n*m + n + m)` where `n*m` is from the existing Levenshtein Search and the `n + m` part comes from traversing the distance matrix to build out the closest matching substring.

### CODE REVIEW

**Comment by mDantas** [comment]
Hey, kkoch986 - when you get a chance, I think this is ready for review.

**Comment by kkoch986** [comment]
@mDantas sorry for the delay will look into it tonight and if alls well merge it

**Comment by mDantas** [comment]
No problem @kkoch986, sounds great. Let me know if I can answer any questions.

**Comment by kkoch986** [comment]
looks great thanks! ill probably bump the version after just checking through a few other things

**Comment by mDantas** [comment]
Awesome, my pleasure @kkoch986 - thanks for the merge!

**Comment by eek** [comment]
Any updates on the version bump? @kkoch986 thanks!

**Pull request merged**
