### PR TITLE
Case Tokenizer

### PR DESCRIPTION
**Pull request by alexlangberg**
As discussed here:

https://github.com/NaturalNode/natural/issues/245

### CODE REVIEW

**Comment by alexlangberg** [comment]
Don't know why the one test failed, probably just needs a restart?

**Comment by kkoch986** [comment]
tried restarting it and it still failed (https://travis-ci.org/NaturalNode/natural/jobs/65937761) i dont see any reason why it should have broken but let me know if you have any ideas

**Comment by alexlangberg** [comment]
Hahaha, what does this even mean? :D

```
npm ERR! weird error 1
npm ERR! not ok code 0
```

I honestly have no idea. It only fails on 0.8 and with a new error since last  time:
```
Error: ENOTEMPTY, rmdir '/home/travis/.nvm/v0.8.28/lib/node_modules/jasmine-node/node_modules'
```

I thought it was a fluke. I'll look into it.

**Comment by kkoch986** [comment]
yea its very weird, if you dont have any luck ill try looking into it a little more when i get some time

**Comment by alexlangberg** [comment]
Found it. All good. :)

**Comment by kkoch986** [comment]
sorry for the delay again, thanks!

**Pull request merged**
