### PR TITLE
Update TS declarations

### PR DESCRIPTION
**Pull request by mdmower**
Update all TS declarations based on current module exports.

Convention:
Reserve export keyword for members of a module that are actually
exported in the corresponding index.js. For everything else, use declare
to make the type/instance available.

Example:
index.js contains: exports.SomeClass = require('...')
index.d.ts should then only have one exported item: export SomeClass ...
and any types needed to support SomeClass use declare.

TODO for maintainer(s) of natural: Lots of class properties and methods
are added that may only be intended for internal use. These can either be
removed or be prefixed with keyword `private`.

### CODE REVIEW

**Comment by mdmower** [comment]
I haven't tested these changes yet (hence draft PR), but early feedback is certainly welcome.

**Comment by mdmower** [comment]
@Hugo-ter-Doest - I am going to keep working my way through the source to add/update TS declarations as I can find time, but I wanted to get your preference on methods and properties in classes that are more for internal use than for consumers of this library.

The classes (defined as functions intended to be called with `new`) don't discern between public and private methods and properties. So, from an "accuracy" point of view, TS declarations that include every method and property would be most correct; they really are available to developers. On the other hand, some of them are probably only meant to be used internally. Unfortunately, there isn't a conclusive way for me to figure out which are meant to be public and which are meant to be private.

Are you ok with every property and method being included in the TS declarations? If not, then after I've finished updating this PR, would you be willing to go through the updated .d.ts files and add `private` access modifiers in front of properties and methods that should not be exposed to end users? For example:

```
export declare class SomeClass {
  type: string
  value: string
  private index: number

  constructor (type: string, value: string)
  getType (): string
  getValue (): string
  private setIndex (type: string, value: string): number
  private getIndex (): number
}
```

**Comment by Hugo-ter-Doest** [comment]
Yes, I am ok with publishing all properties and methods in a first run. Thank you for working on this and improving the TS declarations. My attempt is based on the DefinitelyTyped declarations but these are not complete and I want it to be part of the library instead of being external. 

For most parts of the library I can decide which elements should be private and which public. Keep up the good work.

**Comment by Hugo-ter-Doest** [comment]
At some time in the future I want to add TypeScript tests as well. Now I only have some simple tests that cannot be run automatically as part of the CI pipeline.

**Comment by Hugo-ter-Doest** [comment]
And, if you have time, please check the linter errors. I am applying StandardJS in this library. So it will complain about string quotes (single) and semicolons (which are not allowed).

**Comment by mdmower** [comment]
> And, if you have time, please check the linter errors. I am applying StandardJS in this library. So it will complain about string quotes (single) and semicolons (which are not allowed).

Yep, will do. This looks like forbidden use of `T[]` for non-primitive types. Need to use `Array<T>`. Easy enough, will address soon.

I plan to keep working on this incrementally, so apologies in advance if you get notifications for every "Pull Request Test Coverage Report for Build ..." It just takes too much time to decipher types to handle in one sitting.

**Comment by Hugo-ter-Doest** [comment]
I am merging this now, and checking for members that should become private in a separate PR.

**Pull request merged**
