### PR TITLE
Added json files for portuguese language

### PR DESCRIPTION
**Pull request by EduApps-CDG**
I did translated the english version, but added some words as brazillian language may have more than one words to express the same word in english.

**Example:**
> `prostitute` turns to `puta` or `prostituta` but these words have the same meaning.

### CODE REVIEW

**Comment by EduApps-CDG** [comment]
I could have done better. but there is a huge file that I can't open on my bad laptop. I could have edited some javascript files as well, but I don't know where to start as I'm not used to doing pull requests.

**Comment by Hugo-ter-Doest** [comment]
I will take a look. Thanks for your contribution!

**Comment by EduApps-CDG** [comment]
As I said, I just added JSON files, I didn't touched in js files

**Comment by Hugo-ter-Doest** [comment]
Thanks!

**Comment by EduApps-CDG** [comment]
You are welcome, I needed that update 👍

Em qua, 27 de abr de 2022 11:02, Hugo ter Doest ***@***.***>
escreveu:

**Pull request merged**
