### PR TITLE
Update readme, make var declaration consistent

### PR DESCRIPTION
**Pull request by oscarmorrison**
**Changes**  
- moves all var declaration to invidual lines
 
**To Verify**    
- verify diff 

**Extra information**  
I understand that this is a subject opinion, however towards the bottom of the file variable declaration is all own own lines. Lets update the readme to be consistent, and more readable.

### CODE REVIEW

**Comment by kkoch986** [comment]
nice looks good thanks!

**Comment by oscarmorrison** [comment]
Thanks @kkoch986  (I love this library btw, super great).

Did you mean to merge this? I cant see the commit

**Comment by kkoch986** [comment]
i did sorry about that will do so when i get back

**Comment by oscarmorrison** [comment]
Thankyou @kkoch986 👍

**Comment by oscarmorrison** [comment]
Sorry 😐 @kkoch986 just realized I missed a couple 
https://github.com/NaturalNode/natural/pull/357

**Pull request merged**
