### PR TITLE
chore: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
As alternative to #447

### CODE REVIEW

**Comment by DanielRuf** [comment]
> This PR does not pass. Can I use #447 instead of this one?

It does not because the lockfile is / was outdated as you can see in the CI log.

**Comment by Hugo-ter-Doest** [comment]
Reopened.

**Comment by DanielRuf** [comment]
https://travis-ci.org/NaturalNode/natural/builds/386383693
`npm ci` is about 4 seconds faster but this includes the overhead of upgrading npm

And the lockfile has to be always uptodate.

On the other side the cache is almost as fast as `npm ci` but does not require to update the lockfile.

https://travis-ci.org/NaturalNode/natural/builds/386383103

I would prefer the cache (which can be also combined with the yarn cache).

What do you think?

**Comment by Hugo-ter-Doest** [comment]
I am not an expert in setting up travis, so I'm gonna follow your lead. Plus I have the impression that people are not always updating the package-lock file. 

So, I will merge the PR based on caching.

Hugo

**Pull request closed without merging**
