### PR TITLE
additional stop words

### PR DESCRIPTION
**Pull request by mertkahyaoglu**

### CODE REVIEW

**Comment by bojidar-bg** [comment]
:+1:

**Comment by kkoch986** [comment]
all seems reasonable, just curious, where did you pull this list from?

**Comment by mertkahyaoglu** [comment]
I needed some of them for my project and wanted to add a few more for others. You can see the list in [here](http://www.ranks.nl/stopwords).

**Comment by kkoch986** [comment]
sorry for the delay on this, i wanted to do something a little bigger with this but just havent had the time so dont think its worth holding everything up for it. thanks!

**Pull request merged**
