### PR TITLE
chore: clone last 5 commits

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by Hugo-ter-Doest** [comment]
Is that for improving performance? It is said that in most cases it does not improve performance. https://github.com/travis-ci/travis-ci/issues/4575

Thanks anyway, for looking into the travis build.

Hugo

**Comment by DanielRuf** [comment]
It depends on the diffs and amount of changes. It does not save much but always cloning the last 50 commits might be not necessary.

**Comment by Hugo-ter-Doest** [comment]
Test fails. Will look at this tomorrow.

**Comment by DanielRuf** [comment]
Just push a new empty commit to master.

The build started after I've deleted the branch so Travis can not find the branch in my repo and fails.

https://travis-ci.org/NaturalNode/natural/jobs/386392181#L429

**Comment by DanielRuf** [comment]
`git commit --allow-empty -m 'chore: trigger new build'`

**Comment by DanielRuf** [comment]
Also master is green so nothing to do or worry about: https://github.com/NaturalNode/natural/commits/master

**Comment by Hugo-ter-Doest** [comment]
Ok thanks for your support!

Hugo

**Pull request merged**
