### PR TITLE
dice_coefficient supports single character strings

### PR DESCRIPTION
**Pull request by psnider**
Found a failure when finding the dice coefficient of two single character strings,
which produces a result of *NaN*.

### CODE REVIEW

**Comment by kkoch986** [comment]
good catch, thanks!

**Comment by petersnider-cc** [comment]
Could you please bump the version of the package?
As of right now, npm update gets me version 0.2.1,
which doesn't contain this fix.

Or perhaps I need to do something else?
I modified my package.json to include:
```
        "natural": "0.2.x",
```
then I ran:
```
npm update natural
```

**Comment by petersnider-cc** [comment]
I was able to get the version with my update by modifying my package.json to reference the commit ID:
```
        "natural": "NaturalNode/natural#053c79c302",
```

**Comment by kkoch986** [comment]
sorry for the delay on this guys will try to bump it soon just trying to pack a few more things it to the next patch

**Pull request merged**
