### PR TITLE
Transposition loop should check var i and not var k

### PR DESCRIPTION
**Pull request by dnarkiewicz**
Tranposition loop in JaroWinkler Distance Function needs to be checking first for the existence of a match in the first string using "i" rather than "k"

### CODE REVIEW

**Comment by syzer** [comment]
+1

**Comment by kkoch986** [comment]
hey i know its been awhile but @dnarkiewicz any plans to complete this one?

**Comment by dnarkiewicz** [comment]
Oh, I thought after I had last talked to you I saw someone else checked in something similar so my changes were moot. I will relook at my change to see if it is still relevant. If so I will gladly send it your way.

-Dan

**Comment by Hugo-ter-Doest** [comment]
When I added the option to ignore case, I saw that strings were lower cased in the wrong spot in the <code>distance</code> function. This may have cause wrong calculations. I will look into that.

Hugo

**Comment by syzer** [comment]
guys! its great
but you forgot regression test :D,
or any test

**Pull request closed without merging**
