### PR TITLE
Inflector: Add irregular plural ending with -i, and torso -> torsi

### PR DESCRIPTION
**Pull request by rawpixel-vincent**
alumni
calculi
hippopotami
macrofungi
phoeti
syllabi
trophi

and 
torso -> torsi

### CODE REVIEW

**Comment by kkoch986** [comment]
i think theres a mistake in one of the tests. makes me wonder if something isnt running them?

```
expect(inflector.singularize('alumni')).toBe('cactus');
```

**Comment by rawpixel-vincent** [comment]
Good catch 👍 
Now I don't know why, but yes it appears these tests are not running..

**Comment by rawpixel-vincent** [comment]
there is an issue with the tests indeed 
screen shot 2018-02-06 at 14 46 44

**Comment by Hugo-ter-Doest** [comment]
I don't see the issue with tests on my system. Pull request seems just fine to me. Going to merge it now.

Hugo

**Comment by Hugo-ter-Doest** [comment]
Saw the error in the Travis build. Weird error because there is no code saying <code>let r1 = ''</code> in porter_stemmer_sv.js or in bayes_classifier_spec.js.

I'm going to leave like this. If I clone the module to my systems it tests ok.

If it causes trouble for someone I'd like to know.

Hugo

**Pull request merged**
