### PR TITLE
Added Hindi Aggressive Tokenizer

### PR DESCRIPTION
**Pull request by MukeshSinghBisht**
**Hindi Language aggressive tokenizer.**
* Added Hindi Language aggressive tokenizer which considers language specific symbols to be swallowed.
* And to test them added several test cases as well.
I request fellow maintainers and contributors to review and merge my PR or raise queries or suggest changes.
I would highly appreciate inputs.
Thanks in Advance.

### CODE REVIEW

**Review by Hugo-ter-Doest — CHANGES_REQUESTED** [review]
Please restrict the copyright notice to the file you authored. Now it says that you authored the aggressive tokenizer as a whole. Also remove the line with "Aggressive Tokenization Open-Source License (Version 1.0)" That is not an actually existing license. We are using MIT license.

Otherwise your license text is compatible with MIT license.

**Comment by MukeshSinghBisht** [comment]
> Please restrict the copyright notice to the file you authored. Now it says that you authored the aggressive tokenizer as a whole. Also remove the line with "Aggressive Tokenization Open-Source License (Version 1.0)" That is not an actually existing license. We are using MIT license.
> 
> Otherwise your license text is compatible with MIT license.

Thanks @Hugo-ter-Doest  for your inputs,
I made the the changes regarding license text.

**Comment by Hugo-ter-Doest** [comment]
Thanks for your contribution! Very nice to have a Hindi tokenizer as part of the natural library.

**Comment by MukeshSinghBisht** [comment]
Welcome ! I will try adding more more contributions ahead.

**Comment by Hugo-ter-Doest** [comment]
FYI I added the Hindi tokenizer to the API (index.js and index.d.ts files) and added it to the documentation at https://naturalnode.github.io/natural/

**Pull request merged**
